### ISSUE TITLE
与itemscroller craftaddon不兼容

### ISSUE THREAD

**Issue by snpdzk** [Forgot-Dream/DreamMasaAddition#1]
不兼容https://github.com/wendavid552/itemscroller-crafting-fix
无法启动游戏
[latest.log](https://github.com/Forgot-Dream/DreamMasaAddition/files/15302750/latest.log)

**Comment by Forgot-Dream** [comment]
按理来说不应该，因为我用的检测是跟masagadget一致的，如果没有本模组可以加载masagadget的话，那么应该也可以加载本模组。很迷。

原因是修改版的itemscroller的版本号`craftaddon-1.0.0`并没有通过`>=0.16.0`的版本检查。

晚点再看看。

**Comment by Forgot-Dream** [comment]
@Dependency(value = "itemscoller", versionPredicate = ">=0.16.0", optional = true),

...原来MasaGadget里面这个拼错了，应该是`itemscroller`才对，少了个R，所以能过依赖检测.....更抽象了....
这个项目拼对了....所以用不了....阿巴阿巴

**Comment by Forgot-Dream** [comment]
https://github.com/Forgot-Dream/DreamMasaAddition/releases/tag/0.0.3
