### ISSUE TITLE
1.20.2是否支持）

### ISSUE THREAD

**Issue by aurora969** [Forgot-Dream/DreamMasaAddition#3]
modrinth的描述没有1.20.2，然后版本筛选那显示有1.20.1~1.20.2
如果不支持就打扰了
**===============**
以下是1.20.2问题（0.0.4版本）
进游戏后按e物品栏会直接崩溃，模组设置打开发现忽略nbt找不到ommc标红了
但奔溃是由于快速合成配方书的问题
`java.lang.RuntimeException: Mixin transformation of net.minecraft.class_507 failed`
`Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered`
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector handlePlaceRecipe(Lnet/minecraft/class_636;ILnet/minecraft/class_1860;Z)V in dma.mixins.json:features.quickCraftWithRecipeBook.RecipeBookComponentMixin from mod dma failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap DreamMasaAddition-1.20.1-0.0.4-refmap.json`

**Comment by Forgot-Dream** [comment]
试一下0.1.0版本呢（？）

**Comment by Forgot-Dream** [comment]
再次确认了一下，应该是不支持，1.20.2版本更改了`handlePlaceRecipe(Lnet/minecraft/class_636;ILnet/minecraft/class_1860;Z)V`的方法签名，导致找不到注入目标失败。
