### ISSUE TITLE
ignoreSpecNBTTagsWhenSort在1.20.1似乎无效?

### ISSUE THREAD

**Issue by Ydm2** [Forgot-Dream/DreamMasaAddition#4]
![image](https://github.com/user-attachments/assets/8093d6a3-cedb-4ca8-b3e6-a9c91edad954)
![image](https://github.com/user-attachments/assets/622bd204-94b5-4d9e-973a-e975c4f693f7)
![image](https://github.com/user-attachments/assets/ac77b361-320c-43ce-9e6a-2b78d56a4d76)
![image](https://github.com/user-attachments/assets/ee2fb5b9-0e22-45b8-9088-09d61c147989)

**Comment by Forgot-Dream** [comment]
请尝试使用全部版本打包的ommc（即不带任何MC版本后缀）。因为单独打包的ommc的话，Mod ID实际上是`ommc-1_20_1`而不是`ommc`。本Mod是通过识别是否存在`ommc`这个Mod ID以判断是否要启动注入的。

**Comment by Forgot-Dream** [comment]
https://github.com/Forgot-Dream/DreamMasaAddition/actions/runs/11093140693 可以在原有Mod环境下尝试此CI构建的版本。
