### ISSUE TITLE
与新版的Item Scroller有冲突

### ISSUE THREAD

**Issue by BigTianY** [Forgot-Dream/DreamMasaAddition#5]
DreamMasaAddition版本为0.1.1
Item Scroller0.24.50可以正常使用0.24.51-0.24.53无法进入游戏
几个版本的报错似乎都是一样的,所以只上传了最后一个
[错误报告-2024-11-23-周六_12.29.47.zip](https://github.com/user-attachments/files/17878477/-2024-11-23-._12.29.47.zip)

**Comment by Forgot-Dream** [comment]
确认为兼容性问题，已经提交相关修复，请尝试最新CI构建的版本：https://github.com/Forgot-Dream/DreamMasaAddition/actions/runs/12030348539
